### ISSUE TITLE
error

### ISSUE THREAD

**Issue by itxski** [FrostySo/frostyso.github.io#1]
It says it's connected but when I try to send a pkg file, the message " Failed - Something is wrong with the server. It returned HTTP 500.
I tried a lot of things but didn't come up with a solution. 
Any idea?

ty for answer

**Comment by FrostySo** [comment]
Hi there, 

Could you please tell me the package name, package type (dlc, game, theme, etc.). internet type (WIFI or ethernet) and if you followed steps through modded warfares youtube channel? 

Some theme's fail to send, same as with some DLC and games (known ones are spiderman). This is not because of the sender itself, but rather the homebrew installer having issues. 

If it isn't the pkg itself, it might be your internet settings, or firewall settings preventing it from connecting to your ps4. 

You can follow this tutorial here, to show you how the network settings should be done. 

https://www.youtube.com/watch?v=_w0wfMEAH3I

EDIT: If using ethernet, you will need to follow this one here https://www.youtube.com/watch?v=v04zI5SD07k

You can skip all the steps that require you to download the tools and just hear what he says about the internet settings.
